### ISSUE TITLE
Feature request: Bypass click to call dialog

### ISSUE THREAD

**Issue by stoms12** [amoose136/call_or_sms_contact#1]
I have found that if you change the output of the call function to use apple script instead and use this script:
`do shell script "open tel:" & quoted form of "{query}"
delay 0.5
tell application "System Events" to click button "Call" of front window of application process "FaceTime"`

It bypasses the need to click the call button.

On a side note, how can I modify it to let me call numbers with 9 digits?
In New Zealand most of our landlines have 9 digits.

**Comment by amoose136** [comment]
Hmm I'll test it out in a bit an consider adding to the next version. The yellow magnifying glass contains a regex that check digit length.  It looks like this: `^[0-9]{7}+([0-9]{3,4})?$` It matches digits of length 7 followed optionally by digits of length 3 or 4. Just plop that regex into an editor such as https://regex101.com/ and change it until it matches only with valid numbers of digits for your local region. The parts preceding that block strip the input of all other characters such as { "(" , ")" ,"+" } so you only need to worry about digit length. I've got an idea to add support for local digit length and also international numbers based on an ip address check but it will need to be in a future version.

**Comment by stoms12** [comment]
Sorry I'm not sure what I am supposed to do? How can I make it validate numbers with a length of 9?

**Comment by amoose136** [comment]
Well one permissive way is by changing the above regex to `^[0-9]{7}+([0-9]{2,4})?$` That will make it accept numbers of 7,9,10, or 11 digits.
