### ISSUE TITLE
Incompatible with macOS 10.12.4

### ISSUE THREAD

**Issue by kklliu** [amoose136/call_or_sms_contact#6]
Hi,

First of all, I appreciate you make this great workflow, which save me a lot of time.
Recently, I updated my Mac to newest version, 
and this workflow is not compatible with macOS 10.12.4 and Alfred 3.4.1+.
The Official says we need to install a patch named "alfred-fixum" to run workflows which use old libraries.
I was wondering if you could update this workflow, so we could use this fantastic workflow without patching?
Thanks in advance.

**Comment by amoose136** [comment]
I haven't used the workflow in a while so I hadn't noticed but I will update it.

**Comment by kklliu** [comment]
Thanks a lot!!
In the mean time, I wanna report another issue.
When I type in "call numbers", I have to use my trackpad/mouse to move to the notification and click "call" button.
I remember I could simply press "enter" before.
It seems that system will not focus on the "call button" like old days.
I was wondering if any chances to fix this?
Thank you.

**Comment by greiss122** [comment]
Any updates on an update? I was able to use Fixum (https://github.com/deanishe/alfred-fixum) to get this workflow working again, but it doesn't seem to be able to use contacts. Thanks!

**Comment by amoose136** [comment]
Just now had some time to look at it. It was using an alfred workflow in the directory but the workflow was never actually called so just deleting the directory fixes it at the expense of losing auto-update functionality. I had planned to convert things to python but never got to it so all it was doing was checking for updates in the background.

**Comment by greiss122** [comment]
Cool, thanks for taking the time to check in on it! What do you think about the contacts issue? And, are you able to upload those changes you made, or is it something that I can do easily on my end? Thanks!!

**Comment by amoose136** [comment]
I'm about to upload a quick fix with the "fixum" workflow applied then since the FRC season is over and I have some time again, I'll probably just do a complete recode to fix the other issue and a few others.
